services:
  mongo:
    image: mongo
    container_name: procrastinatr-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./ProcrastinatrAPI
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__MongoDb=${MONGO_CONNECTION}
    depends_on:
      - mongo
    networks:
      - app-network
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: on-failure

volumes:
  mongo-data:

networks:
  app-network:
